// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWb8JQETob9HoghjFuqEeqWQn3AxMwhE',
    appId: '1:981975250465:web:610775ccefb8f3ab879560',
    messagingSenderId: '981975250465',
    projectId: 'mobrada-f0adb',
    authDomain: 'mobrada-f0adb.firebaseapp.com',
    databaseURL: 'https://mobrada-f0adb.firebaseio.com',
    storageBucket: 'mobrada-f0adb.appspot.com',
    measurementId: 'G-H895WZ81XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBic4aw0t7LkjL36DGatBSc0RN2ReWpgN4',
    appId: '1:981975250465:android:6d09304bfefe8060879560',
    messagingSenderId: '981975250465',
    projectId: 'mobrada-f0adb',
    databaseURL: 'https://mobrada-f0adb.firebaseio.com',
    storageBucket: 'mobrada-f0adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESIKU5cr29PIpzpS45i9NQdLswoiRDuM',
    appId: '1:981975250465:ios:4979186d96fd9de3879560',
    messagingSenderId: '981975250465',
    projectId: 'mobrada-f0adb',
    databaseURL: 'https://mobrada-f0adb.firebaseio.com',
    storageBucket: 'mobrada-f0adb.appspot.com',
    iosClientId: '981975250465-kork0oclh3ivavl9jc4mvjr8g82c685g.apps.googleusercontent.com',
    iosBundleId: 'com.example.moBrada2022',
  );
}
